title: Andreja Babic Blog
email: me@dnabic.com
description: >
  Still under construction.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: andreja-babic-9901144
github_username:  dnabic

# Build settings
theme: jekyll-theme-architect
include: ['_pages']
plugins:
  - jekyll-feed
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
